name: docker

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check containr registry enabled
        run: |
          GHCR_ENABLED="true"
          echo "GHCR_ENABLED=${GHCR_ENABLED}"

          DOCKERHUB_ENABLED="false"
          if [ "${{ secrets.DOCKERHUB_USERNAME }}" != "" -a "${{ secrets.DOCKERHUB_TOKEN }}" != "" ]; then
            DOCKERHUB_ENABLED="true"
            if [ -e "README.md" ]; then
              DOCKERHUB_README="true"
            fi
          fi
          echo "DOCKERHUB_ENABLED=${DOCKERHUB_ENABLED}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        if: env.DOCKERHUB_ENABLED == 'true'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        if: env.GHCR_ENABLED == 'true'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            name=ncsa/puppet-enc,enable=${{ env.DOCKERHUB_ENABLED == '' }}
            name=ghcr.io/${{ github.repository_owner }}/puppet-enc,enable=${{ env.GHCR_ENABLED }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        if: github.ref == 'refs/heads/main' && env.DOCKERHUB_README == 'true'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ncsa/puppet-enc
          short-description: ${{ github.event.repository.description }}
